

# This file was *autogenerated* from the file faraw_et_al.sage
from sage.all_cmdline import *   # import sage library

_sage_const_2 = Integer(2); _sage_const_8 = Integer(8); _sage_const_6 = Integer(6); _sage_const_5 = Integer(5); _sage_const_4 = Integer(4); _sage_const_1 = Integer(1); _sage_const_47 = Integer(47); _sage_const_149 = Integer(149); _sage_const_29 = Integer(29); _sage_const_15 = Integer(15); _sage_const_9 = Integer(9); _sage_const_256 = Integer(256); _sage_const_112 = Integer(112)
from sage.crypto.sbox import SBox
f = GF(_sage_const_2 **_sage_const_8 , x, x**_sage_const_8 +x**_sage_const_6 +x**_sage_const_5 +x**_sage_const_4 +_sage_const_1 , repr='int')
fi = f.from_integer
def g(t):
    if t == _sage_const_47 :
        return _sage_const_149 
    return (fi(_sage_const_29 )*fi(t) + fi(_sage_const_15 )) / (fi(_sage_const_8 )*fi(t)+fi(_sage_const_9 ))
sbox = SBox([g(i) for i in range(_sage_const_256 )])
result = list(map(int, 
"""124 18 154 77 3 216 99 81 117 91 112 125 88 32 10 96
227 253 141 194 235 5 111 9 122 37 206 233 156 72 53 51
184 7 20 239 102 22 166 210 192 97 226 27 12 248 79 149
69 59 196 220 132 109 94 168 234 84 15 108 120 52 142 14
25 90 151 205 93 0 26 171 217 41 1 67 224 197 21 198
130 174 231 161 199 153 76 6 144 170 246 221 43 232 29 219
61 229 191 242 195 95 137 225 157 75 39 119 44 98 104 87
115 89 56 110 160 42 31 249 169 222 146 11 245 238 136 247
54 139 200 8 36 46 126 218 121 165 105 16 58 35 135 164
207 230 2 243 63 123 214 80 68 55 183 114 107 208 62 163
252 145 116 250 13 204 127 228 187 113 49 86 159 83 152 244
180 193 57 173 133 128 150 30 40 190 255 240 237 155 85 175
162 47 134 50 60 28 186 177 33 202 176 19 70 209 24 178
71 38 212 48 201 172 129 143 215 188 181 147 158 65 101 100
251 179 182 203 140 223 66 254 64 23 45 189 17 213 131 4
73 211 167 74 78 148 236 185 92 241 82 103 118 106 34 138"""
.replace("\n", " ").split(" ")))
assert result == list(sbox)
assert sbox.nonlinearity() == _sage_const_112 

